# Generated by Django 2.2 on 2019-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('eaddr', models.CharField(max_length=30)),
                ('esalary', models.IntegerField()),
            ],
            options={
                'db_table': 'Employee_Details',
                'managed': True,
            },
        ),
    ]
